baseurl = "/"
languageCode = "en-us"
title = "Tasty Licks"

[params]
  description = "webb"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1

	[[menu.main]]
    name = "Vid"
    url  = "/food"
    weight = 2